/*
 * ADOBE CONFIDENTIAL
 *
 * Copyright 2017 Adobe
 * All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of Adobe and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Adobe and its
 * suppliers and may be covered by U.S. and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Adobe.
 */
module.exports = function(gulp) {
  const fs = require('fs');
  const del = require('del');
  const path = require('path');
  const util = require('../helpers/util');
  
  gulp.task('clean', function() {
    del.sync('./build/**');
    // Prepare build folders
    fs.mkdirSync('./build');
    fs.mkdirSync('./build/css');
    fs.mkdirSync('./build/js');
  });
  
  gulp.task('cleanup', function() {
    const isTLB = util.isTLB();
    const root = isTLB ? 'coral-*' : '';
    
    // Remove empty README generated by gulp docs
    const README = path.join(root, 'README.md');
    if (fs.existsSync(README) && fs.readFileSync(README).toString().trim() === '') {
      del.sync(README);
    }
  
    // Remove generated templates
    const templates = path.join(root, 'src/templates/*.js');
    del.sync(templates);
  
    // Remove generated styles
    const styles = path.join(root, 'src/styles/index.css');
    del.sync(styles);
  });
};
