module.exports = function(gulp) {
  const fs = require('fs');
  const del = require('del');
  const path = require('path');
  const util = require('../helpers/util');
  
  gulp.task('clean', function(done) {
    del.sync('./dist/**');
    // Prepare dist folders
    fs.mkdirSync('./dist');
    fs.mkdirSync('./dist/css');
    fs.mkdirSync('./dist/js');
    
    done();
  });
  
  gulp.task('cleanup', function(done) {
    const isTLB = util.isTLB();
    const root = isTLB ? 'coral-*' : '';
    
    // Remove empty README generated by gulp docs
    const README = path.join(root, 'README.md');
    if (fs.existsSync(README) && fs.readFileSync(README).toString().trim() === '') {
      del.sync(README);
    }
  
    // Remove generated templates
    const templates = path.join(root, 'src/templates/*.js');
    del.sync(templates);
  
    // Remove generated styles
    const styles = path.join(root, 'src/styles/index.css');
    del.sync(styles);
    
    done();
  });
};
