/*
 * ADOBE CONFIDENTIAL
 *
 * Copyright 2017 Adobe Systems Incorporated
 * All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of Adobe Systems Incorporated and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Adobe Systems Incorporated and its
 * suppliers and may be covered by U.S. and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Adobe Systems Incorporated.
 */
module.exports = function(gulp) {
  const fs = require('fs');
  const del = require('del');
  const theme = require('../helpers/theme');
  
  gulp.task('clean', function() {
    del.sync('./build/**');
    // Prepare build folders
    fs.mkdirSync('./build');
    fs.mkdirSync('./build/css');
    fs.mkdirSync('./build/js');
  });
  
  gulp.task('cleanup', function() {
    // Remove empty README generated by gulp docs
    if (fs.existsSync('./README.md') && fs.readFileSync('./README.md').toString().trim() === '') {
      del.sync('./README.md');
    }
  
    // Remove generated templates
    del.sync('./src/templates/*.js');
  
    // Remove generated styles
    del.sync('./src/styles/index.css');
    
    // Remove themed index
    const index = theme.getIndex();
    if (index !== 'index') {
      del.sync(`./${index}.js`);
    }
  });
};
